#
# Module manifest for module 'psdict'
#
# Generated by: santarl
#
# Generated on: 2025-11-20
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'psdict.psm1'

# Version number of this module.
ModuleVersion = '1.1.0'

# ID used to uniquely identify this module
GUID = 'b8f2156b-31ae-495e-9378-484d68d32bac' # You can generate a new one with [guid]::NewGuid()

# Author of this module
Author = 'santarl'

# Company or vendor of this module
CompanyName = 'Melting Ice inc.'

# Copyright statement for this module
Copyright = '(c) 2025 santarl. All rights reserved.'

# Description of the functionality provided by this module.
Description = 'A PowerShell module to look up word definitions using the DICT protocol.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the line below.
FunctionsToExport = @(
    'psdict'
)

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
PrivateData = @{

    PSData = @{

    } # End of PSData hashtable

} # End of PrivateData hashtable

}